/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package App;

import java.awt.*;
import javax.swing.*;
import java.util.HashSet;
import java.util.Set;

/**
 *
 * @author maubr
 */
public class Tournois extends javax.swing.JFrame {
    
    
    
    
    /**
     * Creates new form Tournois
     */
    public Tournois() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        NewComp = new javax.swing.JPanel();
        TextTop3 = new javax.swing.JLabel();
        TextTop5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        NewPlayer = new javax.swing.JPanel();
        TextTop4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AddTeam = new javax.swing.JPanel();
        TextTop7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        SaisirUnMatch = new javax.swing.JPanel();
        TextTop11 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        PanePourLesBouton = new javax.swing.JPanel();
        TextTop1 = new javax.swing.JLabel();
        TextTop2 = new javax.swing.JLabel();
        ButtonMP = new javax.swing.JPanel();
        Icon1 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        ButtonTop100 = new javax.swing.JPanel();
        Icon2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();
        ButtonMyTeam = new javax.swing.JPanel();
        Icon3 = new javax.swing.JLabel();
        txt3 = new javax.swing.JLabel();
        BouttonHistorique = new javax.swing.JPanel();
        Icon4 = new javax.swing.JLabel();
        txt4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MyTournois");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        NewComp.setBackground(new java.awt.Color(113, 73, 139));

        TextTop3.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop3.setForeground(new java.awt.Color(255, 255, 255));
        TextTop3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop3.setText("Créer une nouvelle");

        TextTop5.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop5.setForeground(new java.awt.Color(255, 255, 255));
        TextTop5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop5.setText("Competition");

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\trophy_60px_2.png")); // NOI18N

        javax.swing.GroupLayout NewCompLayout = new javax.swing.GroupLayout(NewComp);
        NewComp.setLayout(NewCompLayout);
        NewCompLayout.setHorizontalGroup(
            NewCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCompLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(NewCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(TextTop3, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                    .addComponent(TextTop5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewCompLayout.setVerticalGroup(
            NewCompLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewCompLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TextTop3)
                .addGap(18, 18, 18)
                .addComponent(TextTop5)
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        NewPlayer.setBackground(new java.awt.Color(113, 73, 139));

        TextTop4.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop4.setForeground(new java.awt.Color(255, 255, 255));
        TextTop4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop4.setText("Créer un joueur");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\player_shirt__60px.png")); // NOI18N

        javax.swing.GroupLayout NewPlayerLayout = new javax.swing.GroupLayout(NewPlayer);
        NewPlayer.setLayout(NewPlayerLayout);
        NewPlayerLayout.setHorizontalGroup(
            NewPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPlayerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextTop4, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        NewPlayerLayout.setVerticalGroup(
            NewPlayerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NewPlayerLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(TextTop4)
                .addGap(58, 58, 58)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        AddTeam.setBackground(new java.awt.Color(113, 73, 139));

        TextTop7.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop7.setForeground(new java.awt.Color(255, 255, 255));
        TextTop7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop7.setText("Ajouter une équipe");

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\book_60px.png")); // NOI18N

        javax.swing.GroupLayout AddTeamLayout = new javax.swing.GroupLayout(AddTeam);
        AddTeam.setLayout(AddTeamLayout);
        AddTeamLayout.setHorizontalGroup(
            AddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextTop7, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        AddTeamLayout.setVerticalGroup(
            AddTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(AddTeamLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TextTop7)
                .addGap(66, 66, 66)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        SaisirUnMatch.setBackground(new java.awt.Color(113, 73, 139));

        TextTop11.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop11.setForeground(new java.awt.Color(255, 255, 255));
        TextTop11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop11.setText("Saisir un match");

        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\ballon_60px.png")); // NOI18N

        javax.swing.GroupLayout SaisirUnMatchLayout = new javax.swing.GroupLayout(SaisirUnMatch);
        SaisirUnMatch.setLayout(SaisirUnMatchLayout);
        SaisirUnMatchLayout.setHorizontalGroup(
            SaisirUnMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaisirUnMatchLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(TextTop11, javax.swing.GroupLayout.DEFAULT_SIZE, 322, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        SaisirUnMatchLayout.setVerticalGroup(
            SaisirUnMatchLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SaisirUnMatchLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(TextTop11)
                .addGap(66, 66, 66)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NewComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SaisirUnMatch, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTeam, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(NewComp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AddTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NewPlayer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SaisirUnMatch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        PanePourLesBouton.setBackground(new java.awt.Color(54, 33, 89));

        TextTop1.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop1.setForeground(new java.awt.Color(255, 255, 255));
        TextTop1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop1.setText("LE GENERATEUR DE TOURNOIS DE ");

        TextTop2.setFont(new java.awt.Font("Segoe UI", 1, 22)); // NOI18N
        TextTop2.setForeground(new java.awt.Color(255, 255, 255));
        TextTop2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        TextTop2.setText("LA FIFA DU MONDE ");

        ButtonMP.setBackground(new java.awt.Color(113, 73, 139));
        ButtonMP.setPreferredSize(new java.awt.Dimension(220, 60));
        ButtonMP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMPMouseClicked(evt);
            }
        });

        Icon1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon1.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\Maison_40px_3.png")); // NOI18N

        txt1.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txt1.setForeground(new java.awt.Color(240, 240, 240));
        txt1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt1.setText("Menus Principal");

        javax.swing.GroupLayout ButtonMPLayout = new javax.swing.GroupLayout(ButtonMP);
        ButtonMP.setLayout(ButtonMPLayout);
        ButtonMPLayout.setHorizontalGroup(
            ButtonMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMPLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon1)
                .addGap(18, 18, 18)
                .addComponent(txt1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonMPLayout.setVerticalGroup(
            ButtonMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMPLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonMPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Icon1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ButtonTop100.setBackground(new java.awt.Color(113, 73, 139));
        ButtonTop100.setPreferredSize(new java.awt.Dimension(220, 60));
        ButtonTop100.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonTop100MouseClicked(evt);
            }
        });

        Icon2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon2.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\statistics_40px_1.png")); // NOI18N

        txt2.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txt2.setForeground(new java.awt.Color(240, 240, 240));
        txt2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt2.setText("Top 100 Joueur");

        javax.swing.GroupLayout ButtonTop100Layout = new javax.swing.GroupLayout(ButtonTop100);
        ButtonTop100.setLayout(ButtonTop100Layout);
        ButtonTop100Layout.setHorizontalGroup(
            ButtonTop100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonTop100Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon2)
                .addGap(18, 18, 18)
                .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonTop100Layout.setVerticalGroup(
            ButtonTop100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonTop100Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonTop100Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Icon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        ButtonMyTeam.setBackground(new java.awt.Color(113, 73, 139));
        ButtonMyTeam.setPreferredSize(new java.awt.Dimension(220, 60));
        ButtonMyTeam.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ButtonMyTeamMouseClicked(evt);
            }
        });

        Icon3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Icon3.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\favori_40px_1.png")); // NOI18N

        txt3.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txt3.setForeground(new java.awt.Color(240, 240, 240));
        txt3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt3.setText("Mes equipes");

        javax.swing.GroupLayout ButtonMyTeamLayout = new javax.swing.GroupLayout(ButtonMyTeam);
        ButtonMyTeam.setLayout(ButtonMyTeamLayout);
        ButtonMyTeamLayout.setHorizontalGroup(
            ButtonMyTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMyTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon3)
                .addGap(18, 18, 18)
                .addComponent(txt3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        ButtonMyTeamLayout.setVerticalGroup(
            ButtonMyTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ButtonMyTeamLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(ButtonMyTeamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Icon3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        BouttonHistorique.setBackground(new java.awt.Color(113, 73, 139));
        BouttonHistorique.setPreferredSize(new java.awt.Dimension(220, 60));
        BouttonHistorique.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BouttonHistoriqueMouseClicked(evt);
            }
        });

        Icon4.setIcon(new javax.swing.ImageIcon("C:\\Users\\maubr\\Documents\\NetBeansProjects\\Tournois\\src\\main\\resources\\historique_40px.png")); // NOI18N

        txt4.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        txt4.setForeground(new java.awt.Color(240, 240, 240));
        txt4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        txt4.setText("Historique des rencontres");

        javax.swing.GroupLayout BouttonHistoriqueLayout = new javax.swing.GroupLayout(BouttonHistorique);
        BouttonHistorique.setLayout(BouttonHistoriqueLayout);
        BouttonHistoriqueLayout.setHorizontalGroup(
            BouttonHistoriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BouttonHistoriqueLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Icon4)
                .addGap(18, 18, 18)
                .addComponent(txt4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        BouttonHistoriqueLayout.setVerticalGroup(
            BouttonHistoriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BouttonHistoriqueLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BouttonHistoriqueLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txt4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Icon4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout PanePourLesBoutonLayout = new javax.swing.GroupLayout(PanePourLesBouton);
        PanePourLesBouton.setLayout(PanePourLesBoutonLayout);
        PanePourLesBoutonLayout.setHorizontalGroup(
            PanePourLesBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ButtonMP, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(ButtonTop100, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(ButtonMyTeam, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(BouttonHistorique, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(TextTop1, javax.swing.GroupLayout.DEFAULT_SIZE, 373, Short.MAX_VALUE)
            .addComponent(TextTop2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanePourLesBoutonLayout.setVerticalGroup(
            PanePourLesBoutonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanePourLesBoutonLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(TextTop1)
                .addGap(35, 35, 35)
                .addComponent(TextTop2)
                .addGap(68, 68, 68)
                .addComponent(ButtonMP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonTop100, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ButtonMyTeam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BouttonHistorique, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(247, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(PanePourLesBouton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanePourLesBouton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void ButtonMPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMPMouseClicked
        ButtonMP.setBackground(new Color(153,113,179));
        ButtonTop100.setBackground(new Color(113,73,139));
        ButtonMyTeam.setBackground(new Color(113,73,139));
        BouttonHistorique.setBackground(new Color(113,73,139));
        jPanel2.setVisible(true);
    }//GEN-LAST:event_ButtonMPMouseClicked

    private void ButtonTop100MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonTop100MouseClicked
        ButtonMP.setBackground(new Color(113,73,139)); 
        ButtonTop100.setBackground(new Color(153,113,179));
        ButtonMyTeam.setBackground(new Color(113,73,139));
        BouttonHistorique.setBackground(new Color(113,73,139));
        jPanel2.setVisible(false);
    }//GEN-LAST:event_ButtonTop100MouseClicked

    private void ButtonMyTeamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ButtonMyTeamMouseClicked
        ButtonMP.setBackground(new Color(113,73,139)); 
        ButtonTop100.setBackground(new Color(113,73,139));
        ButtonMyTeam.setBackground(new Color(153,113,179));
        BouttonHistorique.setBackground(new Color(113,73,139));
        jPanel2.setVisible(false);
    }//GEN-LAST:event_ButtonMyTeamMouseClicked

    private void BouttonHistoriqueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BouttonHistoriqueMouseClicked
        ButtonMP.setBackground(new Color(113,73,139)); 
        ButtonTop100.setBackground(new Color(113,73,139));
        ButtonMyTeam.setBackground(new Color(113,73,139));
        BouttonHistorique.setBackground(new Color(153,113,179));
        jPanel2.setVisible(false);
    }//GEN-LAST:event_BouttonHistoriqueMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tournois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tournois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tournois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tournois.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tournois().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddTeam;
    private javax.swing.JPanel BouttonHistorique;
    private javax.swing.JPanel ButtonMP;
    private javax.swing.JPanel ButtonMyTeam;
    private javax.swing.JPanel ButtonTop100;
    private javax.swing.JLabel Icon1;
    private javax.swing.JLabel Icon2;
    private javax.swing.JLabel Icon3;
    private javax.swing.JLabel Icon4;
    private javax.swing.JPanel NewComp;
    private javax.swing.JPanel NewPlayer;
    private javax.swing.JPanel PanePourLesBouton;
    private javax.swing.JPanel SaisirUnMatch;
    private javax.swing.JLabel TextTop1;
    private javax.swing.JLabel TextTop11;
    private javax.swing.JLabel TextTop2;
    private javax.swing.JLabel TextTop3;
    private javax.swing.JLabel TextTop4;
    private javax.swing.JLabel TextTop5;
    private javax.swing.JLabel TextTop7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    private javax.swing.JLabel txt3;
    private javax.swing.JLabel txt4;
    // End of variables declaration//GEN-END:variables
}
